name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel \
        libncurses5 libncurses5-dev libffi-dev libssl-dev \
        libsqlite3-dev libjpeg-dev libfreetype6-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev llvm libncursesw5-dev \
        xz-utils tk-dev libxml2-dev libxmlsec1-dev liblzma-dev \
        openjdk-17-jdk git unzip wget

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Install Android SDK and Build Tools
      run: |
        mkdir -p "$HOME/android-sdk"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p "$HOME/android-sdk/cmdline-tools"
        mv cmdline-tools "$HOME/android-sdk/cmdline-tools/latest"

        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK
      env:
        ANDROIDSDK: ${{ env.HOME }}/android-sdk
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
